sonar.projectKey=zotero-publication-rankings
sonar.projectName=zotero-publication-rankings
sonar.sourceEncoding=UTF-8

sonar.sources=src,bootstrap.js,update-scripts
sonar.exclusions=dist/**,assets/**
