import json

def generate_data_js():
    """
    Combines all rankings into the plugin's data.js file.
    Reads from sjr_rankings.json, core_rankings.json, abs_rankings.json and ft_50_rankings.json (generated by extract scripts)
    and creates the data.js file for the Zotero plugin.
    """
    
    # Load SJR rankings
    print("Loading SJR rankings...")
    try:
        with open('sjr_rankings.json', 'r', encoding='utf-8') as f:
            sjr_rankings = json.load(f)
        print(f"  Loaded {len(sjr_rankings)} SJR journal rankings")
    except FileNotFoundError:
        print("  ERROR: sjr_rankings.json not found. Run extract_sjr.py first.")
        return
    
    # Load CORE rankings
    print("Loading CORE rankings...")
    try:
        with open('core_rankings.json', 'r', encoding='utf-8') as f:
            core_rankings = json.load(f)
        print(f"  Loaded {len(core_rankings)} CORE conference rankings")
    except FileNotFoundError:
        print("  ERROR: core_rankings.json not found. Run extract_full_core.py first.")
        return

    # Load ABS rankings
    print("Loading ABS rankings...")
    try:
        with open('abs_rankings.json', 'r', encoding='utf-8') as f:
            abs_rankings = json.load(f)
        print(f"  Loaded {len(abs_rankings)} ABS journal rankings")
    except FileNotFoundError:
        print("  ERROR: abs_rankings.json not found. Run extract_abs.py first.")
        return
    
    # Load FT50 rankings
    print("Loading FT50 rankings...")
    try:
        ft_50_rankings = ''
        with open('ft_50_rankings.json', 'r', encoding='utf-8') as f:
            ft_50_rankings = f.read()
    
        print(f"  Loaded {len(ft_50_rankings.splitlines()) - 2} FT50 journal rankings")
    except FileNotFoundError:
        print("  ERROR: ft_50_rankings.json not found. Run extract_ft_50.py first.")
        return
    
    # Generate data.js file
    output_path = '../src/data/data.js'
    print(f"\nGenerating {output_path}...")
    
    with open(output_path, 'w', encoding='utf-8') as f:
        # Write header
        f.write('// Combined SJR Journal Rankings and CORE Conference Rankings\n')
        f.write('// Auto-generated data file from extract_core.py and extract_sjr.py\n')
        f.write('// Use this with rankings.js\n')
        f.write('\n')

        # Write SJR rankings
        f.write('// SJR Journal Rankings (Scimago Journal Rank 2024)\n')
        f.write('// Total journals: ' + str(len(sjr_rankings)) + '\n')
        f.write('var sjrRankings = ')
        json.dump(sjr_rankings, f, indent=2, ensure_ascii=False)
        f.write(';\n\n')
        
        # Write CORE rankings
        f.write('// CORE Conference Rankings (2023 + Historical)\n')
        f.write('// Total conferences: ' + str(len(core_rankings)) + '\n')
        f.write('var coreRankings = ')
        json.dump(core_rankings, f, indent=2, ensure_ascii=False)
        f.write(';\n\n')

        # Write ABS rankings
        f.write('// ABS Rankings\n')
        f.write('// Total journals: ' + str(len(abs_rankings)) + '\n')
        f.write('var absRankings = ')
        json.dump(abs_rankings, f, indent=2, ensure_ascii=False)
        f.write(';\n\n')
    
        # Write FT50 rankings
        # **** Note that ft_50_rankings is not a json formated string ****
        f.write('// FT50 Rankings\n')
        f.write('// Total journals: ' + str(len(ft_50_rankings.splitlines()) - 2) + '\n')
        f.write('var ft50Rankings = ')
        f.write(ft_50_rankings)
        f.write(';\n\n');

    # Calculate file size
    import os
    file_size = os.path.getsize(output_path)
    file_size_mb = file_size / (1024 * 1024)
    
    print(f"\n✓ Successfully generated {output_path}")
    print(f"  File size: {file_size_mb:.2f} MB")
    print(f"  SJR journals: {len(sjr_rankings):,}")
    print(f"  CORE conferences: {len(core_rankings):,}")
    print(f"  ABS journals: {len(abs_rankings):,}")
    print(f"  FT50 journals: {len(ft_50_rankings.splitlines()) - 2}")
    print(f"  Total entries: {len(sjr_rankings) + len(core_rankings) + len(abs_rankings) + len(ft_50_rankings.splitlines()) - 2:,}")
    
    print("\nNext steps:")
    print("  1. cd zotero-rankings-plugin")
    print("  2. .\\build.ps1")
    print("  3. Install the generated .xpi file in Zotero")

if __name__ == '__main__':
    generate_data_js()
